---
variables:
  GIT_DEPTH: 5
  GIT_STRATEGY: fetch
  DOCKER_DRIVER: overlay2
  DOCKER_BUILDKIT: 1
  DOCKER_IMAGE: $CI_REGISTRY_IMAGE:${CI_PIPELINE_ID}
  DOCKER_IMAGE_CACHE: $CI_REGISTRY_IMAGE/tmp:latest

stages:
  - build

build:
  image: docker:27.3.1
  services:
    - docker:27.3.1-dind
  stage: build
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - docker pull $DOCKER_IMAGE_CACHE || true
    - docker build --cache-from $DOCKER_IMAGE_CACHE
      -t $DOCKER_IMAGE_CACHE
      -t $DOCKER_IMAGE
      .
    - docker push $DOCKER_IMAGE
    - docker push $DOCKER_IMAGE_CACHE
