.PHONY: server
server:
	npm run server

.PHONY: worker
worker:
	./worker.sh

.PHONY: chrome
chrome:
	npm run chrome

.PHONY: periodic
periodic:
	npm run periodic

.PHONY: oauth
oauth:
	npm run oauth

.PHONY: metrics
metrics:
	npm run metrics

.PHONY: sockets 
sockets:
	npm run sockets
