.PHONY: server
server:
	npm run server

.PHONY: worker
worker:
	npm run worker

.PHONY: chrome
chrome:
	npm run chrome

.PHONY: periodic
periodic:
	npm run periodic

.PHONY: oauth
oauth:
	npm run oauth

.PHONY: metrics
metrics:
	npm run metrics
